---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alecarnassi
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-api.yaml
images:
  - name: project
    newName: w255mids.azurecr.io/alecarnassi/project
    newTag: "240ad61"