---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: w255
resources:
  - ./namespace.yaml
  - ../../base

patches:
  - path: service-mlapi-lb.yaml
    target:
      kind: Service
      labelSelector: app=project-prediction-service